# Generated by scripts/gen_sync.py from arcbox/_async/sandbox.py — do not edit.
"""Sandbox handles and the client entry point.

A handle holds only the sandbox id and the connection — state is never
cached; ``info()`` always fetches fresh.
"""

from __future__ import annotations

import math
import time
import uuid
from contextlib import suppress
from typing import TYPE_CHECKING

import httpx
from google.protobuf import empty_pb2

from arcbox._boundary import wrap_errors
from arcbox._gen import sandbox_pb2, snapshot_pb2
from arcbox._types import (
    UNCHANGED,
    Capabilities,
    SandboxEvent,
    SandboxInfo,
    SandboxSummary,
    Snapshot,
    Unchanged,
    capabilities_from_proto,
    sandbox_event_from_proto,
    sandbox_info_from_proto,
    sandbox_state_from_proto,
    sandbox_state_to_proto,
    sandbox_summary_from_proto,
    snapshot_from_checkpoint,
    snapshot_from_proto,
)
from arcbox.errors import (
    ArcBoxError,
    ConnectionFailedError,
    ConnectionLostError,
    InvalidArgumentError,
    NotFoundError,
    RequestTimeoutError,
    SandboxStateError,
    TimeoutError,
)

from ._client import ConnectClient
from .commands import Commands
from .files import Files
from .ports import Ports
from .templates import Template

if TYPE_CHECKING:
    from collections.abc import Generator, Iterator, Mapping, Sequence
    from types import TracebackType

    from arcbox._connection import Connection
    from arcbox._types import IdlePolicy, SandboxState

    from ._client import ServerStream

_SANDBOX = "/arcbox.sandbox.v1.SandboxService/"
_SNAPSHOT = "/arcbox.sandbox.v1.SandboxSnapshotService/"

_READY_STATES = (sandbox_pb2.SANDBOX_STATE_READY, sandbox_pb2.SANDBOX_STATE_RUNNING)
_GONE_STATES = (sandbox_pb2.SANDBOX_STATE_STOPPING, sandbox_pb2.SANDBOX_STATE_STOPPED)
_READY_EVENTS = (
    sandbox_pb2.SANDBOX_EVENT_KIND_READY,
    sandbox_pb2.SANDBOX_EVENT_KIND_RUNNING,
    sandbox_pb2.SANDBOX_EVENT_KIND_IDLE,
)
_GONE_EVENTS = (
    sandbox_pb2.SANDBOX_EVENT_KIND_STOPPING,
    sandbox_pb2.SANDBOX_EVENT_KIND_STOPPED,
    sandbox_pb2.SANDBOX_EVENT_KIND_REMOVED,
)

#: How often ``connect`` re-inspects a PAUSING sandbox. The daemon
#: emits ``SANDBOX_EVENT_KIND_PAUSED`` on this edge (CORE-21), but the
#: settle poll predates it and remains the simple, robust route — a
#: poll-to-event-wait conversion is a candidate cleanup, not a bug.
_PAUSE_SETTLE_POLL_SECONDS = 0.5

#: Default overall deadline for ``connect`` in seconds — generous
#: because a checkpoint restore or cold boot legitimately takes a
#: while. ``timeout=None`` disables the bound.
_CONNECT_TIMEOUT_SECONDS = 60.0


def _seconds_to_wire(seconds: float | None) -> int:
    return 0 if seconds is None else math.ceil(seconds)


def _connect_deadline_error(sandbox_id: str) -> TimeoutError:
    return TimeoutError(
        f"connect(timeout) elapsed before sandbox {sandbox_id} was ready",
        suggestion="increase the connect timeout argument",
        context={"id": sandbox_id},
    )


def _budget(deadline: float | None, sandbox_id: str) -> float | None:
    """Seconds left before ``deadline`` (``None`` = unbounded), raising
    the connect timeout once it has passed."""
    if deadline is None:
        return None
    remaining = deadline - time.monotonic()
    if remaining <= 0:
        raise _connect_deadline_error(sandbox_id)
    return remaining


class ArcBox:
    """Client entry point. Holds one resolved connection; every handle it
    creates shares it. The :class:`AsyncSandbox` classmethods are sugar
    over a throwaway instance resolved from options/environment.

    Usable as a context manager: exiting the scope closes the SDK-owned
    HTTP client (handles created from this instance stop working); an
    injected ``Connection.http_client`` is left to its owner."""

    def __init__(self, connection: Connection | None = None) -> None:
        self._client = ConnectClient(connection)
        self._capabilities: Capabilities | None = None

    def close(self) -> None:
        """Close the SDK-owned HTTP client (no-op for an injected one)."""
        self._client.close()

    def capabilities(self) -> Capabilities:
        """What the daemon can do: version, sandbox protocol level,
        feature flags, and whether nested virtualization is available.
        Answered host-side (works before any sandbox exists) and cached
        for the life of this client — a failed fetch is not cached, so
        the next call retries. The SDK does not gate on it: the daemon
        fails fast on its own (a ``CapabilityError`` from ``create``);
        this is the inspectable version of the same answer."""
        if self._capabilities is None:
            with wrap_errors("arcbox.capabilities"):
                self._capabilities = capabilities_from_proto(
                    self._client.unary(
                        _SANDBOX + "GetCapabilities",
                        sandbox_pb2.GetCapabilitiesRequest(),
                        sandbox_pb2.GetCapabilitiesResponse,
                    )
                )
        return self._capabilities

    def __enter__(self) -> ArcBox:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self.close()

    def create(
        self,
        template: str | Template = "",
        *,
        ttl: float | None = None,
        idle_timeout: float | None = None,
        on_idle: IdlePolicy | None = None,
        vcpus: int | None = None,
        memory_mib: int | None = None,
        cmd: Sequence[str] | None = None,
        no_default_cmd: bool = False,
        env: Mapping[str, str] | None = None,
        no_default_env: bool = False,
        labels: Mapping[str, str] | None = None,
        network: bool | None = None,
        wait_until_ready: bool = True,
    ) -> Sandbox:
        """Create a sandbox and (by default) wait until it is READY.

        ``template`` is a Docker image reference, a catalog reference
        (``name[:version]``), or an :class:`AsyncTemplate` instance
        (which pins its exact reference). A catalog template's defaults
        are inherited unless overridden: ``cmd``/``env`` replace/merge
        per the proto contract, and ``no_default_cmd`` /
        ``no_default_env`` suppress the template's default cmd / env
        without supplying replacements.

        ``ttl`` is the hard maximum lifetime — on expiry the daemon
        always destroys the sandbox. ``idle_timeout`` + ``on_idle`` is
        the independent idle-reaping knob; never conflate the two.

        The sandbox id is minted client-side so the readiness
        subscription can be armed BEFORE the create call —
        subscribe-then-act, so no transition is missed (the CORE-67
        rule) — and so retries stay idempotent.
        """
        reference = template if isinstance(template, str) else template.reference
        with wrap_errors("sandbox.create"):
            sandbox_id = str(uuid.uuid4())
            try:
                if wait_until_ready:
                    with self._client.stream(
                        _SANDBOX + "Events",
                        sandbox_pb2.SandboxEventsRequest(sandbox_id=sandbox_id),
                        sandbox_pb2.WatchEventsResponse,
                    ) as events:
                        self._create(
                            sandbox_id,
                            reference,
                            ttl=ttl,
                            idle_timeout=idle_timeout,
                            on_idle=on_idle,
                            vcpus=vcpus,
                            memory_mib=memory_mib,
                            cmd=cmd,
                            no_default_cmd=no_default_cmd,
                            env=env,
                            no_default_env=no_default_env,
                            labels=labels,
                            network=network,
                        )
                        self._wait_ready(sandbox_id, events)
                else:
                    self._create(
                        sandbox_id,
                        reference,
                        ttl=ttl,
                        idle_timeout=idle_timeout,
                        on_idle=on_idle,
                        vcpus=vcpus,
                        memory_mib=memory_mib,
                        cmd=cmd,
                        no_default_cmd=no_default_cmd,
                        env=env,
                        no_default_env=no_default_env,
                        labels=labels,
                        network=network,
                    )
                return Sandbox(self._client, sandbox_id)
            except BaseException:
                # The sandbox may exist even though create() failed
                # (readiness failed, response lost) and ttl is optional,
                # so a leaked VM could run forever. Best-effort removal; a
                # failure here (e.g. nothing was created) must not mask
                # the original error.
                with suppress(Exception):
                    self._client.unary(
                        _SANDBOX + "Remove",
                        sandbox_pb2.RemoveSandboxRequest(id=sandbox_id, force=True),
                        empty_pb2.Empty,
                    )
                raise

    def connect(
        self, sandbox_id: str, *, timeout: float | None = _CONNECT_TIMEOUT_SECONDS
    ) -> Sandbox:
        """Attach to an existing sandbox. A PAUSED sandbox is resumed
        (resume completes once it is READY again); a PAUSING one settles
        to PAUSED first, then resumes; a STARTING one is waited for. A
        terminal state is a typed error carrying the observed state.
        Connecting never touches the sandbox's lifecycle deadlines.

        ``timeout`` bounds the WHOLE call — the settle poll, a resume,
        and the readiness wait share one deadline (default 60s;
        ``None`` or ``math.inf`` disables it). On expiry
        :class:`TimeoutError` is raised and the sandbox is left as it
        was."""
        with wrap_errors("sandbox.connect"):
            # Validate at the boundary: NaN and non-positive values
            # would otherwise corrupt or silently pre-expire the budget
            # arithmetic below.
            if timeout is not None and not timeout > 0:
                raise InvalidArgumentError(
                    "connect timeout must be a positive number of seconds "
                    "(None disables the bound)",
                    context={"timeout": str(timeout)},
                )
            # One deadline over every wait below — the settle poll,
            # resume, and the readiness wait; bounding only one of them
            # would be arbitrary while the neighbouring waits stayed
            # unbounded.
            deadline = (
                None if timeout is None or math.isinf(timeout) else time.monotonic() + timeout
            )
            try:
                return self._connect(sandbox_id, deadline)
            except (RequestTimeoutError, httpx.TimeoutException) as exc:
                # A per-RPC expiry observed after the overall deadline
                # passed is the connect budget surfacing, not the
                # per-request knob.
                if deadline is not None and time.monotonic() >= deadline:
                    raise _connect_deadline_error(sandbox_id) from exc
                raise

    def _connect(self, sandbox_id: str, deadline: float | None) -> Sandbox:
        info = self._inspect(sandbox_id, deadline=deadline)
        # A pausing sandbox's next stop is PAUSED — never READY — so
        # waiting on readiness events would park forever. Poll the
        # checkpoint out, then route on whatever state it settled in.
        while info.state == sandbox_pb2.SANDBOX_STATE_PAUSING:
            remaining = _budget(deadline, sandbox_id)
            time.sleep(
                _PAUSE_SETTLE_POLL_SECONDS
                if remaining is None
                else min(_PAUSE_SETTLE_POLL_SECONDS, remaining)
            )
            info = self._inspect(sandbox_id, deadline=deadline)
        if info.state in _READY_STATES:
            return Sandbox(self._client, sandbox_id)
        if info.state == sandbox_pb2.SANDBOX_STATE_PAUSED:
            # No per-request deadline of its own: restoring a checkpoint
            # takes as long as it takes, and the RPC returns once READY —
            # the overall connect deadline is the only bound.
            self._client.unary(
                _SANDBOX + "Resume",
                sandbox_pb2.ResumeSandboxRequest(id=sandbox_id),
                empty_pb2.Empty,
                timeout=_budget(deadline, sandbox_id),
            )
            return Sandbox(self._client, sandbox_id)
        if info.state == sandbox_pb2.SANDBOX_STATE_STARTING:
            with self._client.stream(
                _SANDBOX + "Events",
                sandbox_pb2.SandboxEventsRequest(sandbox_id=sandbox_id),
                sandbox_pb2.WatchEventsResponse,
                timeout=_budget(deadline, sandbox_id),
            ) as events:
                self._wait_ready(sandbox_id, events, deadline=deadline)
            return Sandbox(self._client, sandbox_id)
        state = sandbox_state_from_proto(info.state)
        raise SandboxStateError(
            f"sandbox {sandbox_id} is {state} and cannot be connected to",
            context={"id": sandbox_id, "state": state, "error": info.error},
        )

    def list(
        self,
        *,
        state: SandboxState | None = None,
        labels: Mapping[str, str] | None = None,
    ) -> Iterator[SandboxSummary]:
        """List sandboxes, auto-paginating server-side pages."""
        with wrap_errors("sandbox.list"):
            page_token = ""
            while True:
                page = self._client.unary(
                    _SANDBOX + "List",
                    sandbox_pb2.ListSandboxesRequest(
                        state=(
                            sandbox_pb2.SANDBOX_STATE_UNSPECIFIED
                            if state is None
                            else sandbox_state_to_proto(state)
                        ),
                        labels=dict(labels) if labels else {},
                        page_token=page_token,
                    ),
                    sandbox_pb2.ListSandboxesResponse,
                )
                for row in page.sandboxes:
                    yield sandbox_summary_from_proto(row)
                page_token = page.next_page_token
                if page_token == "":
                    return

    def restore(
        self,
        snapshot_id: str,
        *,
        ttl: float | None = None,
        labels: Mapping[str, str] | None = None,
        fresh_network: bool = False,
    ) -> Sandbox:
        """Restore a new sandbox from a snapshot. The restored sandbox
        starts READY — there is no boot to wait for. It gets a fresh id,
        minted client-side so retries stay idempotent (the ``create``
        rule); the origin sandbox is untouched.

        ``ttl`` caps the restored sandbox's lifetime in seconds (``None``
        = no limit). ``fresh_network`` assigns a fresh TAP interface and
        IP — required when running several sandboxes restored from the
        same snapshot concurrently."""
        with wrap_errors("snapshots.restore"):
            sandbox_id = str(uuid.uuid4())
            try:
                # No per-request deadline: restoring takes as long as it
                # takes.
                self._client.unary(
                    _SNAPSHOT + "Restore",
                    snapshot_pb2.RestoreRequest(
                        id=sandbox_id,
                        snapshot_id=snapshot_id,
                        labels=dict(labels) if labels else {},
                        network_override=fresh_network,
                        ttl_seconds=_seconds_to_wire(ttl),
                    ),
                    snapshot_pb2.RestoreResponse,
                    timeout=None,
                )
            except BaseException:
                # The sandbox may exist even though restore() failed
                # (response lost) and ttl is optional, so a leaked VM
                # could run forever. Best-effort removal; a failure here
                # (e.g. nothing was restored) must not mask the original
                # error — the create() rule.
                with suppress(Exception):
                    self._client.unary(
                        _SANDBOX + "Remove",
                        sandbox_pb2.RemoveSandboxRequest(id=sandbox_id, force=True),
                        empty_pb2.Empty,
                    )
                raise
            return Sandbox(self._client, sandbox_id)

    def list_snapshots(
        self,
        *,
        sandbox_id: str | None = None,
        labels: Mapping[str, str] | None = None,
    ) -> Iterator[Snapshot]:
        """List the snapshot catalog, auto-paginating server-side pages.
        ``sandbox_id`` keeps only snapshots checkpointed from that
        sandbox; ``labels`` keeps only snapshots carrying all of them."""
        with wrap_errors("snapshots.list"):
            page_token = ""
            while True:
                page = self._client.unary(
                    _SNAPSHOT + "ListSnapshots",
                    snapshot_pb2.ListSnapshotsRequest(
                        sandbox_id=sandbox_id or "",
                        labels=dict(labels) if labels else {},
                        page_token=page_token,
                    ),
                    snapshot_pb2.ListSnapshotsResponse,
                )
                for row in page.snapshots:
                    yield snapshot_from_proto(row)
                page_token = page.next_page_token
                if page_token == "":
                    return

    def delete_snapshot(self, snapshot_id: str) -> None:
        """Delete a snapshot and its on-disk data."""
        with wrap_errors("snapshots.delete"):
            self._client.unary(
                _SNAPSHOT + "DeleteSnapshot",
                snapshot_pb2.DeleteSnapshotRequest(snapshot_id=snapshot_id),
                empty_pb2.Empty,
            )

    def _inspect(self, sandbox_id: str, deadline: float | None = None) -> sandbox_pb2.SandboxInfo:
        """Inspect, with the configured per-RPC deadline capped by the
        remaining connect budget when one is running."""
        remaining = _budget(deadline, sandbox_id)
        request = sandbox_pb2.InspectSandboxRequest(id=sandbox_id)
        if remaining is None:
            return self._client.unary(_SANDBOX + "Inspect", request, sandbox_pb2.SandboxInfo)
        base = self._client.request_timeout
        return self._client.unary(
            _SANDBOX + "Inspect",
            request,
            sandbox_pb2.SandboxInfo,
            timeout=remaining if base is None else min(base, remaining),
        )

    def _create(
        self,
        sandbox_id: str,
        template: str,
        *,
        ttl: float | None,
        idle_timeout: float | None,
        on_idle: IdlePolicy | None,
        vcpus: int | None,
        memory_mib: int | None,
        cmd: Sequence[str] | None,
        no_default_cmd: bool,
        env: Mapping[str, str] | None,
        no_default_env: bool,
        labels: Mapping[str, str] | None,
        network: bool | None,
    ) -> None:
        request = sandbox_pb2.CreateSandboxRequest(
            id=sandbox_id,
            template=template,
            labels=dict(labels) if labels else {},
            cmd=list(cmd) if cmd else [],
            no_default_cmd=no_default_cmd,
            env=dict(env) if env else {},
            no_default_env=no_default_env,
            ttl_seconds=_seconds_to_wire(ttl),
            idle_timeout_seconds=_seconds_to_wire(idle_timeout),
            on_idle=(
                sandbox_pb2.IDLE_ACTION_UNSPECIFIED
                if on_idle is None
                else sandbox_pb2.IDLE_ACTION_KILL
                if on_idle == "kill"
                else sandbox_pb2.IDLE_ACTION_PAUSE
            ),
        )
        if vcpus is not None or memory_mib is not None:
            # Setting either sends `limits`, replacing template defaults
            # WHOLESALE (a zero subfield means the daemon default).
            request.limits.vcpus = vcpus or 0
            request.limits.memory_mib = memory_mib or 0
        if network is not None:
            request.network.mode = (
                sandbox_pb2.NETWORK_MODE_ENABLED if network else sandbox_pb2.NETWORK_MODE_NONE
            )
        self._client.unary(_SANDBOX + "Create", request, sandbox_pb2.CreateSandboxResponse)

    def _wait_ready(
        self,
        sandbox_id: str,
        events: ServerStream[sandbox_pb2.WatchEventsResponse],
        deadline: float | None = None,
    ) -> None:
        """Consume lifecycle events until READY/RUNNING, or fail on a
        terminal transition. The subscription was armed before Create, so
        nothing can be missed; the one residual window — Create processed
        before the subscription registered server-side — is covered by an
        immediate Inspect and by re-inspecting on every keepalive frame."""

        def check(state: int, error: str) -> bool:
            if state in _READY_STATES:
                return True
            if state == sandbox_pb2.SANDBOX_STATE_FAILED:
                raise SandboxStateError(
                    f"sandbox {sandbox_id} failed to start: {error}",
                    context={"id": sandbox_id, "state": "failed", "error": error},
                )
            if state in _GONE_STATES:
                raise SandboxStateError(
                    f"sandbox {sandbox_id} stopped before becoming ready",
                    context={"id": sandbox_id, "state": "stopped"},
                )
            return False

        info = self._inspect(sandbox_id, deadline=deadline)
        if check(info.state, info.error):
            return
        for frame in events:
            # The stream's read timeout only bounds silence; frames may
            # keep arriving (keepalives) without ever tripping it, so the
            # overall budget is re-checked on every frame.
            _budget(deadline, sandbox_id)
            payload = frame.WhichOneof("payload")
            if payload == "event":
                event = frame.event
                if event.kind in _READY_EVENTS:
                    return
                if event.kind == sandbox_pb2.SANDBOX_EVENT_KIND_FAILED:
                    error = event.attributes.get("error", "")
                    raise SandboxStateError(
                        f"sandbox {sandbox_id} failed to start: {error}",
                        context={"id": sandbox_id, "state": "failed", "error": error},
                    )
                if event.kind in _GONE_EVENTS:
                    raise SandboxStateError(
                        f"sandbox {sandbox_id} stopped before becoming ready",
                        context={"id": sandbox_id, "state": "stopped"},
                    )
            elif payload == "keep_alive":
                fresh = self._inspect(sandbox_id, deadline=deadline)
                if check(fresh.state, fresh.error):
                    return
        raise ArcBoxError(
            f"the event stream ended before sandbox {sandbox_id} became ready",
            context={"id": sandbox_id},
        )


class EventStream:
    """A sandbox's lifecycle events, iterable one typed event at a time.

    The iterator ends when the daemon ends the stream. When exiting
    early (``break``), iterate inside the context-manager form —
    ``async with sandbox.events() as stream`` in the async flavor,
    ``with`` in the sync one — so the subscription closes at the break
    instead of whenever the generator finalizer runs."""

    def __init__(self, events: Generator[SandboxEvent]) -> None:
        self._events = events

    def __iter__(self) -> Iterator[SandboxEvent]:
        return self._events

    def close(self) -> None:
        """Cancel the subscription without consuming the rest."""
        self._events.close()

    def __enter__(self) -> EventStream:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self.close()


class Sandbox:
    """A handle to one sandbox."""

    def __init__(self, client: ConnectClient, sandbox_id: str) -> None:
        self._client = client
        # Flipped by the classmethod sugar, whose hidden entry point has
        # no other referent: the handle then closes the client on
        # context exit. Handles minted by a caller-held entry point
        # share its client and never close it.
        self._owns_client = False
        #: Sandbox id.
        self.id = sandbox_id
        #: Run processes inside the sandbox.
        self.commands = Commands(client, sandbox_id)
        #: Move bytes in and out of the sandbox.
        self.files = Files(client, sandbox_id)
        #: Network readiness of the sandbox.
        self.ports = Ports(client, sandbox_id)

    @classmethod
    def create(
        cls,
        template: str | Template = "",
        *,
        ttl: float | None = None,
        idle_timeout: float | None = None,
        on_idle: IdlePolicy | None = None,
        vcpus: int | None = None,
        memory_mib: int | None = None,
        cmd: Sequence[str] | None = None,
        no_default_cmd: bool = False,
        env: Mapping[str, str] | None = None,
        no_default_env: bool = False,
        labels: Mapping[str, str] | None = None,
        network: bool | None = None,
        wait_until_ready: bool = True,
        connection: Connection | None = None,
    ) -> Sandbox:
        """Create a sandbox against the default (or given) connection.
        Parameters as in :meth:`AsyncArcBox.create`. The handle owns the
        hidden entry point's HTTP client and closes it on context exit;
        without the context manager, hold an :class:`AsyncArcBox`
        instead for deterministic cleanup."""
        box = ArcBox(connection)
        try:
            sandbox = box.create(
                template,
                ttl=ttl,
                idle_timeout=idle_timeout,
                on_idle=on_idle,
                vcpus=vcpus,
                memory_mib=memory_mib,
                cmd=cmd,
                no_default_cmd=no_default_cmd,
                env=env,
                no_default_env=no_default_env,
                labels=labels,
                network=network,
                wait_until_ready=wait_until_ready,
            )
        except BaseException:
            box.close()
            raise
        sandbox._owns_client = True
        return sandbox

    @classmethod
    def connect(
        cls,
        sandbox_id: str,
        *,
        timeout: float | None = _CONNECT_TIMEOUT_SECONDS,
        connection: Connection | None = None,
    ) -> Sandbox:
        """Attach to an existing sandbox by id. ``timeout`` bounds the
        whole call as in :meth:`AsyncArcBox.connect` (default 60s;
        ``None`` disables it; expiry raises :class:`TimeoutError`).
        Client ownership works as in :meth:`create`."""
        box = ArcBox(connection)
        try:
            sandbox = box.connect(sandbox_id, timeout=timeout)
        except BaseException:
            box.close()
            raise
        sandbox._owns_client = True
        return sandbox

    @classmethod
    def list(
        cls,
        *,
        state: SandboxState | None = None,
        labels: Mapping[str, str] | None = None,
        connection: Connection | None = None,
    ) -> Iterator[SandboxSummary]:
        """List sandboxes (auto-paginating). The hidden entry point's
        HTTP client closes when iteration completes or the iterator is
        closed; abandoning it mid-iteration defers that to generator
        finalization, so callers that may stop early should hold an
        ArcBox entry point instead (or close the iterator explicitly,
        e.g. ``contextlib.aclosing`` in the async flavor)."""
        with ArcBox(connection) as box:
            for summary in box.list(state=state, labels=labels):
                yield summary

    @classmethod
    def restore(
        cls,
        snapshot_id: str,
        *,
        ttl: float | None = None,
        labels: Mapping[str, str] | None = None,
        fresh_network: bool = False,
        connection: Connection | None = None,
    ) -> Sandbox:
        """Restore a new sandbox from a snapshot — see
        :meth:`AsyncArcBox.restore`. Client ownership works as in
        :meth:`create`."""
        box = ArcBox(connection)
        try:
            sandbox = box.restore(snapshot_id, ttl=ttl, labels=labels, fresh_network=fresh_network)
        except BaseException:
            box.close()
            raise
        sandbox._owns_client = True
        return sandbox

    def info(self) -> SandboxInfo:
        """Fetch the sandbox's current state — always fresh, never cached."""
        with wrap_errors("sandbox.info"):
            return sandbox_info_from_proto(
                self._client.unary(
                    _SANDBOX + "Inspect",
                    sandbox_pb2.InspectSandboxRequest(id=self.id),
                    sandbox_pb2.SandboxInfo,
                )
            )

    def kill(self) -> None:
        """Destroy the sandbox and release all its resources immediately."""
        with wrap_errors("sandbox.kill"):
            self._client.unary(
                _SANDBOX + "Remove",
                sandbox_pb2.RemoveSandboxRequest(id=self.id, force=True),
                empty_pb2.Empty,
            )

    def set_lifecycle(
        self,
        *,
        ttl: float | Unchanged | None = UNCHANGED,
        idle_timeout: float | Unchanged | None = UNCHANGED,
        on_idle: IdlePolicy | Unchanged | None = UNCHANGED,
    ) -> None:
        """Replace lifecycle deadlines. Each knob is tri-state: omitted
        (the :data:`arcbox.UNCHANGED` default) leaves it as it is;
        ``None`` restores the daemon default (no TTL / no idle detection
        / the default idle action) — the same meaning ``None`` has on
        ``create``; a value replaces it. ``ttl`` re-arms the hard cap
        this many seconds from NOW — calling repeatedly keeps a busy
        sandbox alive; ``idle_timeout`` re-arms a live idle timer. Works
        in any non-terminal state, including paused."""
        with wrap_errors("sandbox.set_lifecycle"):
            request = sandbox_pb2.SetLifecycleRequest(id=self.id)
            if not isinstance(ttl, Unchanged):
                request.ttl_seconds = _seconds_to_wire(ttl)
            if not isinstance(idle_timeout, Unchanged):
                request.idle_timeout_seconds = _seconds_to_wire(idle_timeout)
            if not isinstance(on_idle, Unchanged):
                request.on_idle = (
                    sandbox_pb2.IDLE_ACTION_UNSPECIFIED
                    if on_idle is None
                    else sandbox_pb2.IDLE_ACTION_KILL
                    if on_idle == "kill"
                    else sandbox_pb2.IDLE_ACTION_PAUSE
                )
            self._client.unary(_SANDBOX + "SetLifecycle", request, empty_pb2.Empty)

    def events(self) -> EventStream:
        """Subscribe to this sandbox's lifecycle events, yielded as
        typed :class:`SandboxEvent` values (keepalive frames are
        filtered out). The iterator ends when the daemon ends the
        stream; closing the stream (or its context) cancels the
        subscription. A transport drop mid-stream is surfaced as
        :class:`arcbox.errors.ConnectionLostError` — re-subscribing is
        the caller's decision, since missed events cannot be replayed.

        Delivery is best-effort: a slow consumer can lose events, and
        history from before the subscription is gone. This stream is
        filtered to one sandbox while :attr:`SandboxEvent.sequence` is
        stamped globally before that filter — so a sequence gap is
        inconclusive, while contiguous sequences prove nothing was
        missed and a sequence running backwards reveals a daemon
        restart. When in doubt, re-derive state from :meth:`info`."""
        return EventStream(self._stream_events())

    def _stream_events(self) -> Generator[SandboxEvent]:
        with wrap_errors("sandbox.events"):
            delivered = False
            try:
                with self._client.stream(
                    _SANDBOX + "Events",
                    sandbox_pb2.SandboxEventsRequest(sandbox_id=self.id),
                    sandbox_pb2.WatchEventsResponse,
                ) as stream:
                    for frame in stream:
                        # Any frame (keepalives included) marks the
                        # stream live.
                        delivered = True
                        if frame.WhichOneof("payload") == "event":
                            yield sandbox_event_from_proto(frame.event)
            # ConnectionFailedError covers the drop's OTHER wire shape:
            # the daemon losing its upstream event source ends the HTTP
            # stream cleanly with a Connect `unavailable` error frame,
            # decoded into ConnectionFailedError. Daemon-typed errors map
            # to other classes and keep them.
            except (httpx.HTTPError, ConnectionFailedError) as exc:
                if not delivered or isinstance(exc, ConnectionLostError):
                    # Before any frame: an unreachable daemon — nothing
                    # can have been missed (the TS SDK classifies this
                    # identically). ConnectionLostError is already the
                    # stream-death error.
                    raise
                raise ConnectionLostError(
                    "the event stream died",
                    context={"id": self.id},
                    operation="sandbox.events",
                ) from exc

    def pause(self) -> None:
        """Checkpoint the sandbox to disk under the same id and release
        its runtime resources. Resume happens on the next ``connect``
        (or transparently, daemon-side, on the next data-plane call).
        Trades RAM for disk: the checkpoint joins the disk overlay in
        ``storage_bytes`` until the sandbox is resumed or removed.
        Requires a quiescent sandbox (READY — no running command)."""
        with wrap_errors("sandbox.pause"):
            # No per-request deadline: checkpointing takes as long as it
            # takes.
            self._client.unary(
                _SANDBOX + "Pause",
                sandbox_pb2.PauseSandboxRequest(id=self.id),
                empty_pb2.Empty,
                timeout=None,
            )

    def checkpoint(
        self,
        *,
        name: str = "",
        labels: Mapping[str, str] | None = None,
    ) -> Snapshot:
        """Checkpoint this sandbox into a reusable snapshot: paused,
        snapshotted, then resumed, automatically — the sandbox keeps
        running under the same id. Requires a quiescent sandbox (READY —
        no running command). Restore the returned snapshot into fresh
        sandboxes with :meth:`AsyncArcBox.restore`."""
        with wrap_errors("sandbox.checkpoint"):
            recorded = dict(labels) if labels else {}
            # No per-request deadline: checkpointing takes as long as it
            # takes.
            response = self._client.unary(
                _SNAPSHOT + "Checkpoint",
                snapshot_pb2.CheckpointRequest(sandbox_id=self.id, name=name, labels=recorded),
                snapshot_pb2.CheckpointResponse,
                timeout=None,
            )
            return snapshot_from_checkpoint(response, self.id, name, recorded)

    def __enter__(self) -> Sandbox:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        # Scope-exit disposal kills the sandbox so a leaked handle never
        # leaks a VM. Swallows only "already gone" — the whole
        # NotFoundError family, because the daemon does not attach
        # ErrorInfo details yet and a coarse NotFound on this id can only
        # mean the sandbox.
        try:
            with suppress(NotFoundError):
                self.kill()
        finally:
            if self._owns_client:
                self._client.close()
